[google]
project = "visualdb-1046"
zone = "us-east1-d"

[storage]
type = "google"
bucket = "esper"
path = "public"

[database]
# type = "local"
type = "google"
name = "esper-dev-movies2"
user = "dan"
password = "foobar"

[compute]
gpu = false
